### ISSUE TITLE
save BCF as txt file 

### ISSUE THREAD

**Issue by Batir1988** [ivan-usov/FiberApp#13]
Dear all, 

Cool App!! I recently started to use FiberApp and I encountered an issue I am not able to resolve. When using the different persistence length estimation methods I can not save the raw data from the "overview", no window pops up even with "save as txt file" clicked. When I change from "overview" to a different processing length, I obtain the same persistence length for different fibers, as it only depends on this value. I want to have the persistence length for all fitted fibers in my image (separately, if possible) and the raw data (what is fitted). Thank you very much in advance!

**Comment by Batir1988** [comment]
One more question, with which processing length is the overview plot made? Because the results are different from when you introduce an actual processing length. The next thing is there is a minimum processing length (which I assume is the average length of the fibers)...however, I was unsure about this "s" (is this the overall length or the step size for the cosine correlation function).

**Comment by ivan-usov** [comment]
Thank you for you kind feedback! 

- It's, indeed, not possible to save the overview plot data to a text file, because it's usually meant to be used only as a guidance for selecting a `processing length` for the actual persistence length calculation.
- If i remember correctly, fiber selection only affects tracking procedure, meaning, one would select fibers in order to fix their position on image by refitting them with a different alpha/beta/etc parameters. Data analysis runs on *all* fibrils in the current data file independently on a selection. So, if you want to estimate persistence length for different types of fibrils, you need to track/aggregate them in a separate data files. 
- The "overview" produces a plot where each possible processing length is used to calculate the corresponding persistence length for that method, i.e. this is a persistence length vs processing length plot. Possible processing lengths span from a couple of tracking steps up to the longest fiber length.
- I assume, this "s" you mentioned, is the tracking step for fibers, e.g. the distance between points along the tracked chain on image. Thus, this is also the natural step for correlation function and other persistence length estimation functions.
- It would be reasonable to choose processing length to be around the average fibril length. Longer processing lengths will suffer from a lack of statistics, since there are less fibrils contributing.

**Comment by Batir1988** [comment]
Dear Ivan,

thank you very much. This helped a lot!
One last question, is there anyway to obtain the coordinates of the fitted
fibers?

Best,

Batir

**Comment by ivan-usov** [comment]
Hi @Batir1988 , yes, you can extract the coordinates from the saved data files by loading them directly in matlab. Just make sure that matlab knows about [FiberApp/@ImageData/ImageData.m](https://github.com/ivan-usov/FiberApp/blob/master/%40ImageData/ImageData.m) file (i.e. FiberApp folder is added to matlab's Search Path). The pixel coordinates are stored in `xy` and `z` cells (or `xy_nm` and `z_nm` if your images are scaled).

**Comment by ivan-usov** [comment]
@Batir1988 I'm going to close the issue, but feel free to ask if you have more questions.

**Comment by Batir1988** [comment]
Dear Ivan,

thanks for your help. I have still a question that came up when plotting
the data myself. FOr the persistence length calculation, we would like to
look at the spread of the data (each curve or length that is averaged). I
know you mentioned if we want to obtain separate averages for each fiber we
should do it separately. However, the curve when for example calculating
the BCF is an average of all fibers fitted. Is not possible to get all
curves for which the average is calculated so we can see how the data are
spread? (see attached image as an example).
Also in the overview there are an error and R2 values, is this calculated
from the fitting of each fiber length?
I am not sure if the weights that are saved in the txt file take this into
consideration, from what I understand they are only the amount of points of
the fibers, right?
Have a good summer
Best wishes,

Batir

**Comment by ivan-usov** [comment]
Hi @Batir1988 , i'm not sure I fully understand all questions, but here is a few comments that might be helpful. 

Each fiber contributes statistics to every segment separation along its contour (e.g. not only to its full length value), and FiberApp averages statistics from all fibrils for each fitting step. If you want to plot BCF (or any other analysis) for each fiber individually, you'll need to write a separate script and process fiber coordinates extracted from your data files. You can have a look at how it's done if FiberApp with a loop over all fibers, and adapt the function correspondingly (save each curve, instead of summing them up for averaging):
https://github.com/ivan-usov/FiberApp/blob/master/%2Balgorithm/BCF.m

The error and R2 values are related to the averaged curve fitting. There is no fitting of individual fibers, because persistence length is a collective characteristic (and not a characteristic of individual fibrils).

Yes, those are numbers of how many times a value was calculated for each individual separation among all fibrils (see https://github.com/ivan-usov/FiberApp/blob/master/%2Balgorithm/BCF.m for details).
